### PR TITLE
Removed Google log ins for Local Deployments git push (CU-86dtx3b7n)

### PR DESCRIPTION
**Pull request by Darrickg**
- added if statements that will disable google log ins if the dev environment is local
- dev environment is determined by env value in .env file

Test Plan:

- [x] passes linter
- [x] runs properly in local and dev

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-86dqq93dp Deadlocks Fix - Update logSensorsVital and getMostRecentSessionWithLocationid db.js functions](https://app.clickup.com/t/86dqq93dp)

**Comment by trisapeace** [comment]
Task linked: [CU-86dtx3b7n Create a local App.js for particle-accelerator that doesn't use the Google login](https://app.clickup.com/t/86dtx3b7n)

**Comment by Darrickg** [comment]
fixed name

**Comment by Darrickg** [comment]
runs good in dev

**Review by micahdbak — APPROVED** [review]
Great!

**Pull request merged**
