### PR TITLE
Upgrade Node to 18.16.1 (CU-860raw01r)

### PR DESCRIPTION
**Pull request by tmackinnon**
- [As of Oct 11 2023](https://docs.digitalocean.com/release-notes/app-platform/#october-2023): Ubuntu 22 is the default stack for Digital Ocean apps which now supports Node v18 
- Updating Node from v16 to v18 as v16's end-of-life is Sep 2023
- Upgraded Travis to run on Ubuntu 22 (jammy) for compatibility with Node v18 and to match Digital Ocean's default Ubuntu version - as per similar node update in [BraveSensors](https://github.com/bravetechnologycoop/BraveSensor/commit/ad6ea8f817f26f326057926d49e9c6b24868e54e)
- Added `"engines"` to package.json file to ensure correct node version is used - as per Digital Ocean [documentation](https://docs.digitalocean.com/products/app-platform/reference/buildpacks/nodejs/#ubuntu-2204-stack-supporting-nodejs-18)

Test Plan
- [x] Ensure Travis passes
- [x] Deploy to Dev and ensure there's no build errors
- [x] Once deployed on Dev, check node version in console on Digital Ocean platform

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-860raw01r Update NodeJS for PA](https://app.clickup.com/t/860raw01r)

**Comment by trisapeace** [comment]
Task linked: [CU-860raw01r Update NodeJS for PA](https://app.clickup.com/t/860raw01r)

**Review by micahdbak — APPROVED** [review]
I was writing a question about the change from Bionic Beaver to Focal Fossa, but I see that it's for compatibility with Node v18---thanks for clarifying that in the description.

I must ask---is Jammy Jellyfish (Ubuntu 22.X.X) compatible with Node v18? If it is, it might be better to have Travis run that version instead of Focal Fossa (Ubuntu 20.X.X), because it matches DigitalOcean's default Ubuntu version.

Apart from that, looks good!

**Comment by tmackinnon** [comment]
> I was writing a question about the change from Bionic Beaver to Focal Fossa, but I see that it's for compatibility with Node v18---thanks for clarifying that in the description.
> 
> I must ask---is Jammy Jellyfish (Ubuntu 22.X.X) compatible with Node v18? If it is, it might be better to have Travis run that version instead of Focal Fossa (Ubuntu 20.X.X), because it matches DigitalOcean's default Ubuntu version.
> 
> Apart from that, looks good!

Thanks Micah and very good point! I had used focal to follow what happened in BraveSensor when we upgraded Node, but you make a good point that it would probably be best to match what's being used by Digital Ocean. I've updated the Travis file and all checks have passed.

**Review by trisapeace — COMMENTED** [review]
Nice. I agree that matching the Ubuntu used on Digital Ocean is the way to go.

I'm surprised that the `package-lock.json` file stayed the same. 

@tmackinnon , could you please try running `npm install` and see if the `engine` and other changes are then also reflected in the `package-lock.json`? If it's different, could you please create a pull request for those differences?

Travis uses `npm ci` to get its dependencies, so it will be using `package-lock.json` instead of `package.json` to determine what it needs. I'm not sure whether DigitalOcean uses `npm ci` or `npm install` in its process.

**Comment by tmackinnon** [comment]
@trisapeace It looks like in a subsequent dependabot PR ended up adding `"engines": {"node": "18.16.1"}` to the `package-lock.json` so I think it should be okay!

**Pull request merged**
