### PR TITLE
Removed door sensor pairing page (CU-860ravwq2)

### PR DESCRIPTION
**Pull request by elanawood**
Removed the door sensor pairing page since it is unused.

### CODE REVIEW

**Comment by trisapeace** [comment]
Task linked: [CU-860ravwq2 Remove PA Door Sensor Pairing page](https://app.clickup.com/t/860ravwq2)

**Review by Darrickg — COMMENTED** [review]
LGTM! Travis is failing the PR task because of something I'm fixing in a separate branch, wait for my PR to merge then u can merge yours!

**Comment by Darrickg** [comment]
merged fixes to main, please pull from it then you can merge :)

**Comment by Darrickg** [comment]
merge from main (again LOL) once i merge my fix branch and travis should be happy. feel free to merge to main after :) (for real this time)

**Review by Darrickg — APPROVED** [review]
looks like it works now :) feel free to merge (once johnny/micah approves too)

**Review by Darrickg — CHANGES_REQUESTED** [review]
I completely forgot about line removals ;-;

There are some things you need to remove (such as things in Pages.js and HomeView) related to the door sensor pairing page.

**Comment by Darrickg** [comment]
oh and some files under components

**Comment by micahdbak** [comment]
Make sure that the following files are updated when you update this PR:

```
	deleted:    src/components/DoorSensorPairing/DoorSensorEntryCard.jsx
	deleted:    src/components/DoorSensorPairing/DoorSensorQueueCard.jsx
	deleted:    src/components/DoorSensorPairing/QueueStatusBadge.jsx
	modified:   src/upper-level-components/Frame.jsx
	modified:   src/upper-level-components/Pages.js
	deleted:    src/views/DoorSensorPairing.jsx
	modified:   src/views/HomeView.jsx
```

**Review by micahdbak — APPROVED** [review]
Changes look good! If the deployment to dev is alright, I'm happy with this PR

**Review by Darrickg — APPROVED** [review]

**Pull request merged**
